### ISSUE TITLE
how to get all session objects, in order to restore them next time i start hapi-server?

### ISSUE THREAD

**Issue by jt3k** [hapijs/hapi-auth-cookie#110]
I need to store session objects in the database,
to restore session objects from the database, when I turn hapi-server again

How can I:
1. store  session objects ?
2. restore session objects ?

**Comment by mtharrison** [comment]
Why restore them in bulk? You could just read the DB/cache for each incoming request with a session ID stored in the cookie, kind of how the example in this project's README works.

**Comment by Marsup** [comment]
I don't think that's necessary if you only want it for server restarts. Cookies already contain the full encrypted authentication and shouldn't stop working just because of a restart.

**Comment by jt3k** [comment]
> @mtharrison wrote:
> Why restore them in bulk?

To restore them all is needed so i can use `request.auth.isAuthenticated` as written in the example.

> @Marsup wrote:
> Cookies already contain the full encrypted authentication and shouldn't stop working just because of a restart.

Just try to run this example to make sure that after server reboot you have to go through authorization again.

**Comment by mtharrison** [comment]
Not sure I understand your point. The user's cookie is decrypted and `request.auth` is populated for every single request to your server. So whether the server has been rebooted recently or not is irrelevant. The cookie still resides on the user's machine.

**Comment by jt3k** [comment]
@mtharrison 

All right. After server restarts, on the client cookies are not deleted. But on the server the session data will be reset.

My goal is to store sessions in the database, to restore them when I restart the server.

I don't know how to get the list of session data using hapi

If this is not the right way, then tell me how to do what I want. (if you understand what I mean)

**Comment by Marsup** [comment]
OK I think I understand the confusion. There are no sessions with this plugin.

The example in the readme makes use of an in-memory cache (`request.server.app.cache.set` + `cache.get`) to store some data (not a session) associated with the login and only stores an id in the cookie, but you're not forced to do that if your data is rather small. You can trust the encryption to safely provide you with the information, and it's way more scalable because there's no database hit at all.

Now if you *really* want a database to store more things than a cookie could handle, you have several options :
- based on the readme, you'll need to setup catbox (the hapi cache provider) with a database with one of the [catbox plugins](https://www.npmjs.com/search?q=catbox)
- do your own stuff in validateFunc and login, basically replacing those 2 cache calls with whatever you want to persist something

I'll also insist that the example in the readme should NOT be used in production as it starts its unique identifier from 1 and it should really be unique as said in the comment.

**Comment by jaw187** [comment]
:+1: on the last post by @Marsup 

You'll have to setup some type of persistent store for the session data and then the cookie should contain an index that references the session.

**Comment by jt3k** [comment]
@Marsup  ok, thanks for you answer!
but u not understand me.

**Comment by jt3k** [comment]
i start the example

open in browser
set name and password
after this in my browser sets cookie `sid-example` ![](https://i.imgur.com/1OM4MH7.png)
but i can't find this key in my server-side ![](https://i.imgur.com/fPKkLNb.png);

How to get this value? 
![](https://i.imgur.com/OTXvySx.png)

**Comment by Marsup** [comment]
As I have already said :
- there is no session so you won't find that cookie anywhere in the server
- the cache is in-memory but if you plug it to a database it will be there on restart

**Comment by jt3k** [comment]
@Marsup  ok! thnx!
