### ISSUE TITLE
Distinguish validation error and not valid

### ISSUE THREAD

**Issue by matthieusieben** [hapijs/hapi-auth-cookie#157]
in the code there is a `if (err || !isValid)`, treating both cases in the same way.

The error may, typically, come from a database error, which, because of this check, is not even logged. Additionnaly, if the login failed because of an internal error, there is no reason to clear the cookie (clearInvalid) in that case, since the problem is not with the cookie.

Could you provide a better error handling for this ?

I would suggest using the following logic:
```js
if (err) {
  if (err.isBoom && err.output.statusCode === 401) {
    // Treat Boom.unauthorized() as validation errors
    isValid = false;
  } else {
    return reply(err, null, result);
  }
}

if (!isValid) {
  // ...
}
```
Which, basically, skips clearing the cookies, and the redirectTo if an internal error occurs.

**Comment by matthieusieben** [comment]
2 years later you label this as `non-issue`. Great support!

**Comment by hueniverse** [comment]
> 2 years later you label this as non-issue, close it, without a single comment. Great support!
-- @matthieusieben 

Let's dig into that, shall we?

If you still use this module after two years, you have been using a huge amount of my work for a long time which should have entitled me to some basic respect. While **I** don't take sarcasm and hostile behavior personally, many open source maintainers do and this kind of interaction is the reason open source is in such bad shape. You can try arguing that this wasn't a big deal but it is a huge deal.

**The hostility in your one line comment is unacceptable.**

Instead, you could have just asked why I closed this issue without comment. It's that simple. Again - given the amount of open source work I maintain, and that you have used, you should have given me the benefit of the doubt that there was a reason for my action. That's just common decency and professional courtesy.

This is a two years old issue. It was opened when someone else was maintaining this module. It never received any attention from anyone, including yourself who never followed up about it.

The code it is referencing is no longer there. It was last used a year ago [here](https://github.com/hapijs/hapi-auth-cookie/blob/v7.1.0/lib/index.js#L172) in version 7.1.0 which is only compatible with hapi v16 which is being deprecated in a week and in general, no improvements have been made to any v16 related plugins for over a year now.

I closed the issue and marked it as a non-issue because:
- I assumed you didn't care about this anymore given the total lack of follow-up
- I assumed no one else cared about it given the lack of any feedback for two years
- I looked for the code this was discussing and noticed it was no longer relevant as-is
- The place where this specific issue is present is in a branch that we no longer maintain expect for critical bugs and security issues (and that also ends in a week for v16).

Now, I closed the issue without any comment because I very reasonably assumed you moved on. Either you learned to live with it, stopped using this module, or stopped using hapi. That's usually the case when someone opens an issue and leaves it for 2 years with zero follow-up. If you applied a tiny fraction of your frustration in the above response to the actual issue, you might have gotten some result from the previous maintainers or other members of the community.

I don't need to spend valuable time and resources posting explanations on 2 years old issues that no one cares about. It is not a good use of my time. But if you really cared and wanted to know why I did that, you could have simply asked. It's really not that hard. Let me demonstrate:

"Hey @hueniverse, can you explain to me why you closed the issue without comment and marked it as a non-issue?"
