### ISSUE TITLE
Auth cookie does not set instantly

### ISSUE THREAD

**Issue by captainjackrana** [hapijs/hapi-auth-cookie#159]
Using hapi v15.1.1 & hapi-auth-cookie v7.0.0, I have my default auth strategy defined as - 
```
server.auth.strategy('tyler', 'cookie', {
        password: 'alpha_beta_gamma_delta_bravo_charlie,
        ttl: 15 * 24 * 3600 * 1000,
        cookie: 'tyler-auth', // Name of cookie to set
        isSecure: false // Set to true in production with https
        clearInvalid: true
    });
server.auth.default('tyler');
```
In my login route handler, after setting the auth cookie, I redirect request to a desired page ( the page he was looking for before login)
```
request.cookieAuth.set({id: 'alpha'});
return reply.redirect('/account');
```
Now the **account** route has an auth mode **'required'**. However, it still gives me a 401 error. Pasting the request log here 
`{ '0': 
   { request: '1493921651841:local:21834:j2aqdbu5:10041',
     timestamp: 1493921651841,
     tags: [ 'received' ],
     data: 
      { method: 'get',
        url: '/account',
        agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36' },
     internal: true },
  '1': 
   { request: '1493921651841:local:21834:j2aqdbu5:10041',
     timestamp: 1493921651842,
     tags: [ 'auth', 'unauthenticated', 'missing', 'tyler' ],
     data: 
      { data: null,
        isBoom: true,
        isServer: false,
        output: 
         { statusCode: 401,
           payload: { statusCode: 401, error: 'Unauthorized' },
           headers: { 'WWW-Authenticate': 'cookie' } },
        reformat: [Function],
        message: 'Unauthorized',
        isMissing: true },
     internal: true } }`

It seems that the **tyler** auth is still missing. 
Weirdly, however, when I refresh the page, the **account** route passes through which means the auth was set after the login, but was not applied instantly. What could be the reason for this?

**Comment by captainjackrana** [comment]
I have also noticed this happening with Chrome and not with Firefox

**Comment by sholladay** [comment]
What you are experiencing is a bug in Chrome. Any effect that `isSameSite` may or may not have is just further weirdness coming from Chrome.

The problem is that Chrome does not respect the `Set-Cookie` header for a redirect. In other words, it will not include the cookie when making the request to `/account` when that request was triggered by a redirect **AND** the cookie was set on the redirect response (e.g. `307`). However, it will include the cookie in all future requests.

I found this out the hard way. And I came up with a pretty amusing hack. Instead of `reply.redirect()`, do this...

```
reply('<script>location.href=\'/account\'</script>')
```

It works because it does not rely upon a redirect, but instead uses a client-side script to direct the browser to your target URL. So Chrome will send the cookie, as expected.

This is a pretty serious bug, in my opinion. I'm surprised there isn't a ton of noise around it. There is just a [long neglected issue](https://bugs.chromium.org/p/chromium/issues/detail?id=150066) and a new one that, so far, is [getting only crickets](https://bugs.chromium.org/p/chromium/issues/detail?id=150066)..

**Comment by captainjackrana** [comment]
Well that's a wonderful catch @sholladay 
I'm just wondering if this also has anything to do with the issue i'd raised earlier for which you had posted too @sholladay. 
Are the fb cookies not being set since its a redirection call after authorization on facebook?

**Comment by sholladay** [comment]
You are referring to https://github.com/hapijs/bell/issues/287, right? That does seem plausible. I haven't tested Safari for this redirect bug, only Chrome and Firefox. The bug might have come from WebKit, as it's been around for years based on the issues I linked to above.

**Comment by wallacepeng** [comment]
looked at the example 
    request.server.app.cache.set(sid, { account: account }, 0, (err) => {

        if (err) {
            return reply(err);
        }

        request.cookieAuth.set({ sid: sid });
        return reply.redirect('/account');
    });
it seems same as what you described and worked. I am using hapi 16.x.

**Comment by sholladay** [comment]
@wallacepeng `server.app` is meant for storing arbitrary runtime state. Did you mean `server.cache`? I don't see how that would affect this, since that is for server-side caching of expensive computations. But the server's response does not seem to be at fault here, as far as I can tell.

There is a pretty minimal repro case for the Chrome bug here: https://pastebin.com/ENiwCVdC

**Comment by albatrocity** [comment]
@sholladay thanks for the explanation and the workaround, this saved me a lot of headache. I can confirm that this was only an issue for me in Chrome (not Safari) and that the script injection works.

**Comment by sholladay** [comment]
Hmm, I found a [StackOverflow answer](https://stackoverflow.com/a/42220786) that theorizes this is some sort of security feature that can be avoided by setting the `SameSite` cookie attribute to `Lax`. Haven't tried it, though. Doesn't make sense to me and still seems like a bug.

**Comment by JamesTheHacker** [comment]
Wow, I would have never figured the solution out if it wasn't for this issue. Solved it for me.

I am using the `bell` with the Facebook provider for Facebook logins. When the user accepts the application permissions and is redirected back to my site I then set a cookie using `hapi-auth-cookie`. I think this have been related because when I wasn't using `hapi-auth-cookie` and I didn't have that problem.

Thanks anyway.
