### ISSUE TITLE
artifacts is a duplicate of credentials

### ISSUE THREAD

**Issue by tranan89** [hapijs/hapi-auth-cookie#195]
Why is artifcats a duplicate of credentials?
We are not using artifacts so this just feels like extra payload without any gain.
Can we get rid of it somehow?

Example
{ 
isAuthenticated: true,
credentials: {
      caregiver: [Object],
      scope: [Array],
      databaseName: '...',
      tenant: '...' 
},
artifacts: { 
     caregiver: [Object],
     scope: [Array],
    databaseName: '...',
     tenant: '...' 
},
strategy: 'ttl',
mode: 'required',
error: null 
},

**Comment by mrlannigan** [comment]
The authentication artifacts are used in the request decorator (`request.cookieAuth`) that is provided to allow the request handler to manage the session state for that request. It is useful to keep the state of the session in the artifacts because it allows the `validateFunc` to do what it pleases to the `credentials` object without affecting the operation of the `cookieAuth` decorator mentioned above. 

As an aside, in the situation you are not using a `validateFunc`, both the `credentials` and `artifacts` properties are referencing the same object and so while it might seem like it's a duplicate object, it's actually 2 references to the same object in memory. See the following for code references:
* https://github.com/hapijs/hapi-auth-cookie/blob/ca2e2d5131796b94e8b484bed0540a9c5d02fe33/lib/index.js#L161
* https://github.com/hapijs/hapi-auth-cookie/blob/ca2e2d5131796b94e8b484bed0540a9c5d02fe33/lib/index.js#L193

> Can we get rid of it somehow?

I do not see any reason at this point to change the way we are passing around request/session specific objects. If you feel otherwise, let's continue this conversation and maybe you can provide some profiling examples or other possible reasons to pivot.
