### ISSUE TITLE
request.auth.credentials undefined after calling request.auth.session.set

### ISSUE THREAD

**Issue by Zambonilli** [hapijs/hapi-auth-cookie#48]
I think this is more of a question than an issue.  In my login page I'd like to perform the login, set the credentials and then display the user's authenticated dashboard without redirecting to the dashboard url.  It looks like when I call reply.view with the request.auth.credentials after calling request.auth.session.set it is undefined.  Is this because the credentials are set earlier in the pipeline and calling set doesn't update until the next request?

IE:
// do login stuff and get a user object that we want to save in session
request.auth.session.set(user);

reply.view('dashboard', { user: request.auth.credentials });

**Comment by jaw187** [comment]
This is because `request.auth.session.set` is used for setting the cookie object.  `request.auth.credentials` is only set after a request is successfully validated against an auth scheme.  In the case of your route, the request is unsuccessfully authenticated, your validation logic is executed, and the cookie is set.  But `request.auth.credentials` was already set to null and `request.auth.session.set` isn't going to update it.

The most straight forward approach would be to separate your dashboard and login logic, then use reply with `reply.redirect('/dashboard')` upon successful user validation.

However, you can use the `onPreAuth` extension point in the request life cycle to do things differently if you'd like.  http://hapijs.com/api#request-lifecycle

**Comment by Zambonilli** [comment]
Thanks for the quick response.  This is what I figured was happening.  I'll just take the performance hit of the reply.redirect because it's more pragmatic.

**Comment by technowar** [comment]
I am using `XMLHttpRequest`. How should I separate my login logic, and use `reply.redirect`?

**Comment by Zambonilli** [comment]
I would just handle the redirect to /home client side in javascript if you're doing an ajax call.  It seems a little cleaner that way too if you're using ajax for navigation logic.  My guess is that the browsers have weird behavior with following a redirect from an ajax request.

**Comment by technowar** [comment]
Can you show me your code, please?

**Comment by jaw187** [comment]
You won't be able to use a redirect.  If you're concerned about requesting protected resources via an ajax requests, you'll need to handle errors to trigger the logic to get user/pass within your own client app.

`request.auth.credentials` will be available on all subsequent requests, but not immediately after setting the session.

The browser is handling the ajax request as expected.  The random value is the encrypted cookie which will be used on your future requests.

**Comment by technowar** [comment]
@jaw187, am I doing this the right way?

**Comment by jaw187** [comment]
The redirect is disabled correctly.  Your handler needs to be able to reply with an error.  This is how I'd write your handler and I'd use Boom (https://github.com/hapijs/boom)...

```
            }, function (error, data) {
                
                if (error) {
                    return reply(Boom.wrap(error));
                }

                if (data && data.length) {
                    request.auth.session.set(data[0]);
                    return reply(data[0]);
                }
                
                return reply(Boom.unauthorized());
            });
```

From that point on it all depends on the implementation of your client app.

**Comment by technowar** [comment]
@jaw187, thank you. And sorry @Zambonilli for trying to hijack your issue.
